cantonade/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
admin.autodiscover()

from librairie.views import TagTexteList, AuteurTexteList, TexteDetailView, AuteurList, TagList, RecentTexteList

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    (r'^$', RecentTexteList.as_view()),

    (r'^tag/$', TagList.as_view()),
    (r'^auteur/$', AuteurList.as_view()),    
    (r'^tag/([\w-]+)/$', TagTexteList.as_view()),
    (r'^auteur/([\w-]+)/$', AuteurTexteList.as_view()),
    (r'^texte/(?P<slug>[a-z0-9-]+)/$', TexteDetailView.as_view()),
)

urlpatterns += patterns('django.contrib.flatpages.views',
    url(r'^colophon/$', 'flatpage', {'url': '/colophon/'}, name='colophon'),
    url(r'^index/$', 'flatpage', {'url': '/index/'}, name='index'),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

librairie/models.py
from django.db import models
from datetime import datetime
from django.contrib.flatpages.models import FlatPage
from django.utils import timezone

class IndexFlatPage(FlatPage):
    subtitle = models.TextField(verbose_name="deuxieme titre", blank=True, null=True)

class Auteur(models.Model):
    nom=models.CharField(max_length=255)
    prenom=models.CharField(max_length=255, blank=True, null=True)
    slug=models.CharField(max_length=255)
    bio=models.TextField(blank=True, null=True)

    def __unicode__(self):
        if self.prenom:
            return self.nom+', '+self.prenom
        else:
            return self.nom

class Tag(models.Model):
    tag=models.CharField(max_length=255)
    slug=models.CharField(max_length=255, unique=True)

    def __unicode__(self):
        return self.tag

class Texte(models.Model):
    auteur=models.ForeignKey(Auteur)
    titre=models.CharField(max_length=255)
    slug=models.CharField(max_length=255)
    description=models.TextField(blank=True, null=True)
    tags=models.ManyToManyField(Tag)
    html = models.TextField()
    epub = models.FileField(upload_to="livres-epub", blank=True, null=True)
    pdf = models.FileField(upload_to="livres-pdf", blank=True, null=True)
    date_creation = models.DateTimeField(auto_now_add=True)
    date_modification = models.DateTimeField(auto_now=True)
    publique = models.BooleanField(default=False)
    date_de_publication = models.DateTimeField(default=datetime.now, blank=True, null=True, verbose_name="date et heure de publication")

    def __unicode__(self):
        return self.titre+' ('+unicode(self.auteur)+')'

    @property
    def visible(self):
        now = timezone.now().astimezone(timezone.get_current_timezone())
        if not self.publique or self.date_de_publication > now:
            return False
        return True

librairie/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.http import Http404
from django.views.generic import ListView, DetailView
from librairie.models import Auteur, Tag, Texte, IndexFlatPage
from datetime import datetime
from django.contrib.admin.views.decorators import staff_member_required
from django.utils import timezone

class RecentTexteList(ListView):

    template_name = 'librairie/recent_textes.html'

    def get_context_data(self, **kwargs):
        context = super(RecentTexteList, self).get_context_data(**kwargs)
        context['flatpage'] = self.flatpage
        return context

    def get_queryset(self):
        self.flatpage = get_object_or_404(IndexFlatPage, url='/index/')
        now = timezone.now().astimezone(timezone.get_current_timezone())
        return Texte.objects.filter(publique=True, date_de_publication__lte=now).order_by('-date_de_publication')


class AuteurTexteList(ListView):

    template_name = 'librairie/textes_par_auteur.html'

    def get_context_data(self, **kwargs):
        context = super(AuteurTexteList, self).get_context_data(**kwargs)
        context['auteur'] = self.auteur
        return context

    def get_queryset(self):
        self.auteur = get_object_or_404(Auteur, slug=self.args[0])
        now = timezone.now().astimezone(timezone.get_current_timezone())
        return Texte.objects.filter(auteur=self.auteur, publique=True, date_de_publication__lte=now).order_by('-date_de_publication')

class TagTexteList(ListView):

    template_name = 'librairie/textes_par_tag.html'

    def get_context_data(self, **kwargs):
        context = super(TagTexteList, self).get_context_data(**kwargs)
        context['tag'] = self.tag
        return context

    def get_queryset(self):
        self.tag = get_object_or_404(Tag, slug=self.args[0])
        return Texte.objects.filter(tags=self.tag)


class AuteurList(ListView):

    queryset = Auteur.objects.all().extra(select={'imf': 'UPPER(nom)'}, order_by=['imf'])
    context_object_name = 'auteur_list'
    model = Texte


class TagList(ListView):

    queryset = Tag.objects.order_by('tag')
    context_object_name = 'tag_list'
    model = Texte


class TexteDetailView(DetailView):

    model = Texte

    def get_object(self):
        object = super(TexteDetailView, self).get_object()
        now = timezone.now().astimezone(timezone.get_current_timezone())
        if not object.visible and not self.request.user.is_staff:
            raise Http404
        return object

librairie/templates/librairie/auteur_list.html
{% extends "librairie/base.html" %}

{% block title %}La cantonade - les auteurs{% endblock %}

{% block bodyclass %}list{% endblock %}

{% block page_title %}
<a class="h1" href="#">auteurs</a>
{% endblock page_title %}


{% block page_details %}
{% endblock %}

{% block page_lower %}
<div id="lower-container" > 
  <div id="text-list">
    {% for auteur in auteur_list %}
<a href='/auteur/{{auteur.slug}}' class="big-tag">{{auteur.prenom}} {{auteur.nom}}</a>
{% endfor %}
  </div>
</div>
{% endblock %}

librairie/templates/librairie/base.html
<html>
    <head>

        <title>{% block title %}La cantonnade{% endblock %}</title>

        <meta charset="utf-8">

        <link rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/cantonade.css">

        {% block media %}
        {% endblock %}

    </head>
    <body class="{% block bodyclass %}{% endblock %}">

        <div id="upper-container">

              <div id="top-container"> 
              <div id="nav">
                <a href="/tag">tags</a> ⧫ <a href="/auteur">auteurs</a> ⧫ <a href="/colophon">colophon</a>
              </div>

                <div id="top-content">

                    <a id="site-title" href="/">La cantonade</a>


                </div>
              </div>


              <div id="book-title">
                {% block page_title %}

                {% endblock %}
              </div>

                {% block page_details %}
                  <div id="book-details">
    
                  </div>
                {% endblock %}

        </div>

        {% block page_lower %}

            <div id="lower-toptoe"> 
              <div id="lower-toptoe-center">
              </div>
            </div>

            <div id="lower-container"> 
              <div id="book-content">
              </div>
            </div>

            <div id="lower-toe"> 
              <div id="lower-toe-center">
              </div>
            </div>

        {% endblock %}

    </body>
</html>

librairie/templates/librairie/ckeditor.html
<p><textarea{{ final_attrs|safe }}>{{ value }}</textarea></p>
<script type="text/javascript">
    if (typeof CKEDITOR == "undefined") {
        $( document ).ready(function() {
            CKEDITOR.replace("{{ id }}", {{ config|safe }});
        });
    } else {
        CKEDITOR.replace("{{ id }}", {{ config|safe }});
    }
</script>

librairie/templates/librairie/recent_textes.html
{% extends "librairie/base.html" %}

{% load humanize %}

{% block media %}
    <script src="/static/js/jquery-1.10.2.js"></script> 
    <script> 
    $(function(){
      $(".button#lire").click(function(){
        $("#book-content").slideToggle("slow", function(){
            $("#book-content").load("{{MEDIA_URL}}{{texte.html}}");
            $("#book-content").addClass("filled");
            $("#lower-toptoe").addClass("filled");
            $("#lower-toe-center").addClass("filled");
            $("#lower-container").addClass("filled");
        });
        $("#book-content").slideToggle("fast");
      });
    });
    </script> 
{% endblock %}



{% block title %}{{flatpage.title}}{% endblock %}



{% block page_title %}
    <a class="h1" href="#">{{flatpage.title}}&nbsp;</a><a class="h2" href="#">&nbsp;{{flatpage.subtitle}}&nbsp;</a>
{% endblock %}

{% block page_details %}
    <div id="book-details">
        <div id="description">
            {{flatpage.content|safe}}
        </div>
    </div>
{% endblock %}

{% block page_lower %}
<div id="lower-toptoe" class="filled"> 
  <div id="lower-toptoe-center" class="filled">
            <span class="heading">Récemment édités:</span>
  </div>
</div>

<div id="lower-container" class="filled"> 
  <div id="text-list" class="filled">
    <div class="textes">
    {% for texte in texte_list %}
    <div class="text">
    <a href='/texte/{{texte.slug}}' class="title">{{texte.titre}}</a><span class="author"><a href='/auteur/{{texte.auteur.slug}}'>{{texte.auteur.prenom}} {{texte.auteur.nom}}</a></span>
    
            <div class="text-tags"><div class='text-date'>{{texte.date_de_publication|naturalday}}</div>{% for tag in texte.tags.all %}<a href="/tag/{{tag.slug}}" class="tag">{{tag.tag}}</a> 
            {% endfor %}
            </div>
    

    </div>
    {% endfor %}
    </div>
  </div>
</div>

<div id="lower-toe"> 
  <div id="lower-toe-center" class="filled">
  </div>
</div>
{% endblock %}

librairie/templates/librairie/tag_list.html
{% extends "librairie/base.html" %}

{% block title %}La cantonade - les tags{% endblock %}

{% block bodyclass %}list{% endblock %}

{% block page_title %}
<a class="h1" href="#">tags</a>
{% endblock %}

{% block page_details %}
{% endblock %}

{% block page_lower %}
<div id="lower-container" > 
  <div id="text-list">
{% for tag in tag_list %}
<a href='/tag/{{tag.slug}}' class="big-tag">{{tag.tag}}</a>
{% endfor %}
  </div>
</div>
{% endblock %}

librairie/templates/librairie/texte_detail.html
{% extends "librairie/base.html" %}

{% block media %}
    <script src="{{STATIC_URL}}js/jquery-1.10.2.js"></script> 
    <script> 
    $(function(){
      $(".button#lire").click(function(){
        $("#book-content").slideToggle("slow", function(){
            $("#book-content").addClass("filled");
            $("#lower-toptoe").addClass("filled");
            $("#lower-toe-center").addClass("filled");
            $("#lower-container").addClass("filled");
        });
        $("#book-content").slideToggle("fast");
      });
    });
    </script> 
{% endblock %}


{% block title %}La cantonade - {{texte.titre}}, {{texte.auteur}}{% endblock %}

        {% block page_title %}
            {% if not texte.visible %}
                <span class="preview-text">mode aperçu texte non publié</span><br><br>
            {% endif %}
            <a class="h1" href="#">{{texte.titre}}&nbsp;</a><a class="h2" href="/auteur/{{texte.auteur.slug}}">&nbsp;{{texte.auteur.prenom}} {{texte.auteur.nom}}&nbsp;</a>
        {% endblock %}


        {% block page_details %}
          <div id="book-details">
                <div id="tags">
                {% for tag in texte.tags.all %}
                <a href="/tag/{{tag.slug}}" class="tag">{{tag.tag}}</a> 
                {% endfor %}
                </div>
                
                
                <div id="description">
                {{texte.description|safe}}
                </div>
                
                <div id="buttons">
                <a class="button" id="lire">Lire en ligne</a>
                {% if texte.pdf %}<a class="button" href="{{MEDIA_URL}}{{texte.pdf}}" target="_blank">.pdf format zine</a>{% endif %}
                {% if texte.epub %}<a class="button" href="{{MEDIA_URL}}{{texte.epub}}" target="_blank">.epub</a>{% endif %}
                </div>    
          </div>
        {% endblock %}

{% block page_lower %}
<div id="lower-toptoe"> 
  <div id="lower-toptoe-center">
  </div>
</div>

<div id="lower-container"> 
  <div id="book-content">
  {{texte.html|safe}}
  </div>
</div>

<div id="lower-toe"> 
  <div id="lower-toe-center">
  </div>
</div>
{% endblock %}

librairie/templates/librairie/textes_par_auteur.html
{% extends "librairie/base.html" %}

{% load humanize %}

{% block title %}La cantonade - {{auteur.prenom}} {{auteur.nom}}{% endblock %}

{% block page_title %}
<a class="h1" href="/auteur/">auteur&nbsp;</a><a class="h2" href="#">&nbsp;{{auteur.prenom}} {{auteur.nom}}</a>
{% endblock %}


{% block bodyclass %}tag{% endblock %}

{% block page_details %}
                  <div id="book-details" class="author">

            <div id="description">
            {{auteur.bio|safe}}
            </div>
<br>&nbsp;
</div>
{% endblock %}


{% block page_lower %}



<div id="lower-toptoe" class="filled"> 
  <div id="lower-toptoe-center" class="filled">
            <span class="heading">Textes</span>
  </div>
</div>

<div id="lower-container" class="filled"> 
  <div id="text-list" class="filled">
    <div class="textes">
    {% for texte in texte_list %}
    <div class="text">
    <a href='/texte/{{texte.slug}}' class="title">{{texte.titre}}</a>
            <div class="text-tags"><div class='text-date'>{{texte.date_de_publication|naturalday}}</div>{% for tag in texte.tags.all %}<a href="/tag/{{tag.slug}}" class="tag">{{tag.tag}}</a> 
            {% endfor %}
            </div>
    </div>
    {% endfor %}
    {% if not texte_list %}
    <div class="text no-texts">
        Aucun texte édité
    </div>
    {% endif %}
    </div>
  </div>
</div>

<div id="lower-toe"> 
  <div id="lower-toe-center" class="filled">
  </div>
</div>
{% endblock %}

librairie/templates/librairie/textes_par_tag.html
{% extends "librairie/base.html" %}

{% load humanize %}

{% block title %}La cantonade - {{tag.tag}}{% endblock %}

{% block bodyclass %}tag{% endblock %}

{% block page_title %}
<a class="h1" href="/tag/">tag&nbsp;</a><a class="h2" href="#">&nbsp;{{tag}}</a>
<br>&nbsp;{% endblock %}

{% block page_details %}
{% endblock %}


{% block page_lower %}



<div id="lower-toptoe" class="filled"> 
  <div id="lower-toptoe-center" class="filled">
  </div>
</div>

<div id="lower-container" class="filled"> 
  <div id="text-list" class="filled">
    <div class="textes">
    {% for texte in texte_list %}
    <div class="text">
    <a href='/texte/{{texte.slug}}' class="title">{{texte.titre}}</a><span class="author"><a href='/auteur/{{texte.auteur.slug}}'>{{texte.auteur.prenom}} {{texte.auteur.nom}}</a></span>
            <div class="text-tags"><div class='text-date'>{{texte.date_de_publication|naturalday}}</div>{% for tag in texte.tags.all %}<a href="/tag/{{tag.slug}}" class="tag">{{tag.tag}}</a> 
            {% endfor %}
            </div>
            </div>
    </div>
    {% endfor %}
    </div>
  </div>
</div>

<div id="lower-toe"> 
  <div id="lower-toe-center" class="filled">
  </div>
</div>
{% endblock %}